steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [ "build", "-t", "gcr.io/${PROJECT_ID}/jokes-generator-tg-api:${REVISION_ID}", "tg" ]
    env:
      - 'MODEL_URL=http://model_api:8888/'
      - 'TZ=Asia/Tbilisi'
    secretEnv: [ 'TG_API_TOKEN', 'NEWS_API_TOKEN' ]

  - name: gcr.io/cloud-builders/docker
    args:
      [ "build", "-t", "gcr.io/${PROJECT_ID}/jokes-generator-web:${REVISION_ID}", "web" ]
    env:
      - 'MODEL_URL=http://model_api:8888/'
      - 'TZ=Asia/Tbilisi'
    secretEnv: [ 'FLASK_SECRET_KEY' ]

  - name: gcr.io/cloud-builders/docker
    args:
      [ "build", "-t", "gcr.io/${PROJECT_ID}/jokes-generator-model-api:${REVISION_ID}", "api" ]
    env:
      - 'MODEL_NAME=naltukhov/joke-generator-rus-t5'
      - 'MODEL_REVISION=latest'
      - 'MODEL_API_PORT=8888'
      - 'TZ=Asia/Tbilisi'


images:
  - 'gcr.io/$PROJECT_ID/jokes-generator-tg-api'
  - 'gcr.io/$PROJECT_ID/jokes-generator-web'
  - 'gcr.io/$PROJECT_ID/jokes-generator-model-api'


availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/TG_API_TOKEN
      env: TG_API_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/NEWS_API_TOKEN
      env: NEWS_API_TOKEN
    - versionName: projects/${PROJECT_ID}/secrets/FLASK_SECRET_KEY
      env: FLASK_SECRET_KEY

options:
  logging: CLOUD_LOGGING_ONLY