version: '3.9'
services:
  tgapi:
    image: nikitosl/jokes-generator-tgapi
    build: tg
    depends_on:
      - genapi
      - genweb
    environment:
      TG_API_TOKEN: ${TG_API_TK}
      NEWS_API_TOKEN: ${NEWS_API_TK}
      TZ: ${TZ}

  genapi:
    image: nikitosl/jokes-generation-api
    build: api
    environment:
      TZ: ${TZ}

  genweb:
    image: nikitosl/jokes-generation-web
    build: web
    depends_on:
      - genapi
    ports:
      - "5555:5555"
    environment:
      TZ: ${TZ}