version: '3.9'
services:
  tg_publisher:
    image: nikitosl/jokes-generator-tg-api
    build: tg_publisher
    depends_on:
      - model_api
      - web
    environment:
      TG_API_TOKEN: ${TG_API_TK}
      NEWS_API_TOKEN: ${NEWS_API_TK}
      MODEL_URL: ${MODEL_URL}
      TZ: ${TZ}

  web:
    image: nikitosl/jokes-generation-web
    build: web
    depends_on:
      - model_api
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      MODEL_URL: ${MODEL_URL}
      PORT: ${WEB_PORT}
      TZ: ${TZ}

  model_api:
    image: nikitosl/jokes-generation-model-api
    build: api
    environment:
      MODEL_NAME: ${MODEL_NAME}
      MODEL_REVISION: ${MODEL_REVISION}
      PORT: ${MODEL_API_PORT}
      TZ: ${TZ}