version: '3.9'
services:
  genapi:
    image: nikitosl/jokes-generation-api
    build: api

  genweb:
    image: nikitosl/jokes-generation-web
    build: web
    depends_on:
      - genapi
    ports:
      - "5555:5555"