version: '3.9'
services:
  ${TG_SERVICE_NAME}:
    image: nikitosl/jokes-generator-tg-api
    build: tg_publisher
    depends_on:
      - ${MODEL_SERVICE_NAME}
      - ${WEB_SERVICE_NAME}
    environment:
      TG_API_TOKEN: ${TG_API_TK}
      NEWS_API_TOKEN: ${NEWS_API_TK}
      MODEL_URL: ${MODEL_URL}
      TZ: ${TZ}

  ${WEB_SERVICE_NAME}:
    image: nikitosl/jokes-generation-web
    build: web
    depends_on:
      - ${MODEL_SERVICE_NAME}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      MODEL_URL: ${MODEL_URL}
      PORT: ${WEB_PORT}
      TZ: ${TZ}

  ${MODEL_SERVICE_NAME}:
    image: nikitosl/jokes-generation-model-api
    build: api
    environment:
      MODEL_NAME: ${MODEL_NAME}
      MODEL_REVISION: ${MODEL_REVISION}
      PORT: ${MODEL_API_PORT}
      TZ: ${TZ}