steps:
  # Build image for TG-PUBLISHER
  - name: gcr.io/cloud-builders/docker
    secretEnv: [ 'TG_API_TOKEN', 'NEWS_API_TOKEN' ]
    entrypoint: bash
    args:
      - -c
      - |
        docker build -t gcr.io/${PROJECT_ID}/${_TG_SERVICE_NAME}:$COMMIT_SHA --build-arg=MODEL_URL=http://${_MODEL_SERVICE_NAME}:8080/ --build-arg=TZ=Asia/Tbilisi --build-arg=TG_API_TOKEN=$$TG_API_TOKEN --build-arg=NEWS_API_TOKEN=$$NEWS_API_TOKEN tg_publisher

  # Push TG-PUBLISHER image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ "push", "gcr.io/${PROJECT_ID}/${_TG_SERVICE_NAME}:$COMMIT_SHA" ]

images:
  - 'gcr.io/$PROJECT_ID/${_TG_SERVICE_NAME}:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/tg-bot-token/versions/latest
      env: 'TG_API_TOKEN'
    - versionName: projects/${PROJECT_ID}/secrets/news-api-token/versions/latest
      env: 'NEWS_API_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
